/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IhgButton {
        "disabled": boolean;
        "label": string;
        "type": 'primary' | 'secondary';
    }
    interface KAvatar {
        "size"?: 'small' | 'medium' | 'large';
    }
    interface KBanner {
        "type": 'success' | 'error';
    }
    interface KBannerText {
    }
    interface KBreadcrumbs {
    }
    interface KBreadcrumbsItem {
        "current": boolean;
    }
    interface KButton {
        "color"?: 'primary' | 'secondary' | 'terciary';
        "disabled"?: boolean;
        "elevation"?: boolean;
        "shape"?: 'full' | 'round' | 'smooth';
        "size"?: 'large' | 'medium' | 'small';
    }
    interface KCard {
    }
    interface KCarousel {
        "showDots": boolean;
        "steps": number;
        "transitionDuration": number;
    }
    interface KCarouselItem {
    }
    interface KCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "value"?: string;
    }
    interface KCollapseItem {
        "disabled": boolean;
    }
    interface KCollapseList {
    }
    interface KCollapseMenu {
        "position": 'right' | 'left';
    }
    interface KCollapseParent {
    }
    interface KColumn {
        "fluid"?: boolean;
        "size"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizelg"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizemd"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizesm"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizexl"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
    }
    interface KDialog {
    }
    interface KDialogActions {
    }
    interface KDialogBody {
    }
    interface KDialogContent {
    }
    interface KDialogHeader {
    }
    interface KDivider {
    }
    interface KDropdown {
        "color": 'primary' | 'secondary' | 'terciary';
        "disabled": boolean;
        "helperText"?: string;
        "label": string;
        "validationState"?: '' | 'success' | 'error';
        "variant"?: 'button' | 'input' | 'table';
    }
    interface KDropdownItem {
        "checked": boolean;
        "disabled"?: boolean;
        "name": string;
        "value": string;
    }
    interface KElevation {
        "radius"?: string;
    }
    interface KGrid {
        "fluid"?: boolean;
    }
    interface KIcon {
        "name": | 'alert-circle'
    | 'assistant'
    | 'attachment'
    | 'bookmark-border'
    | 'bookmark'
    | 'cached'
    | 'check-circle'
    | 'close'
    | 'cloud-upload'
    | 'colorize'
    | 'delete'
    | 'done'
    | 'drag-indicator'
    | 'edit'
    | 'event'
    | 'file-copy'
    | 'finish-1'
    | 'finish-2'
    | 'finish-3'
    | 'flip-camera-ios'
    | 'school'
    | 'highlight-off'
    | 'info'
    | 'insert-drive-file'
    | 'keyboard-arrow-down'
    | 'keyboard-arrow-left'
    | 'keyboard-arrow-right'
    | 'keyboard-arrow-up'
    | 'menu'
    | 'network-wired'
    | 'notifications-active'
    | 'notifications'
    | 'person'
    | 'photo-camera'
    | 'playlist-add-check'
    | 'question-answer'
    | 'remove-red-eye'
    | 'ribbon'
    | 'search'
    | 'settings'
    | 'supervised-user-circle'
    | 'swap-vert'
    | 'swap-vert-down'
    | 'swap-vert-up'
    | 'tune'
    | 'view-week'
    | 'visibility-off'
    | 'add-circle'
    | 'bookmarks'
    | 'dashboard';
        "size"?: 'small' | 'medium' | 'large' | 'extra-large';
    }
    interface KImg {
        "alt"?: string;
        "fit"?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down';
        "height"?: number;
        "src": string;
        "width"?: number;
    }
    interface KInput {
        "disabled"?: boolean;
        "helperText"?: string;
        "label": string;
        "maxLength"?: number;
        "minLength"?: number;
        "name"?: string;
        "type": 'text' | 'password' | 'email' | 'tel' | 'url' | 'number';
        "validationState"?: '' | 'success' | 'error';
        "value"?: string;
    }
    interface KLabel {
    }
    interface KListGroup {
    }
    interface KListItem {
    }
    interface KMenu {
        "disableDrawer": boolean;
        "hideDrawerLg": boolean;
        "hideDrawerMd": boolean;
        "hideDrawerSm": boolean;
        "hideDrawerXl": boolean;
        "hideDrawerXs": boolean;
        "menuKey": string;
    }
    interface KMenuContent {
    }
    interface KMenuNav {
    }
    interface KModal {
        "hideCloseButton": boolean;
        "show": boolean;
    }
    interface KNotification {
        "notificationCount": number;
    }
    interface KNotificationGroup {
    }
    interface KNotificationItem {
        "alertColor": string;
        "isRead"?: boolean;
        "label": string;
        "time"?: string;
    }
    interface KPaginator {
        "currentPage"?: number;
        "totalPages": number;
    }
    interface KProgressBar {
        "value": number;
    }
    interface KRadioButton {
        "checked": boolean;
        "disabled"?: boolean;
        "name": string;
        "value": string;
    }
    interface KRadioButtonGroup {
    }
    interface KRow {
        "spacing"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface KTab {
    }
    interface KTabItem {
        "current": boolean;
        "disabled": boolean;
    }
}
declare global {
    interface HTMLIhgButtonElement extends Components.IhgButton, HTMLStencilElement {
    }
    var HTMLIhgButtonElement: {
        prototype: HTMLIhgButtonElement;
        new (): HTMLIhgButtonElement;
    };
    interface HTMLKAvatarElement extends Components.KAvatar, HTMLStencilElement {
    }
    var HTMLKAvatarElement: {
        prototype: HTMLKAvatarElement;
        new (): HTMLKAvatarElement;
    };
    interface HTMLKBannerElement extends Components.KBanner, HTMLStencilElement {
    }
    var HTMLKBannerElement: {
        prototype: HTMLKBannerElement;
        new (): HTMLKBannerElement;
    };
    interface HTMLKBannerTextElement extends Components.KBannerText, HTMLStencilElement {
    }
    var HTMLKBannerTextElement: {
        prototype: HTMLKBannerTextElement;
        new (): HTMLKBannerTextElement;
    };
    interface HTMLKBreadcrumbsElement extends Components.KBreadcrumbs, HTMLStencilElement {
    }
    var HTMLKBreadcrumbsElement: {
        prototype: HTMLKBreadcrumbsElement;
        new (): HTMLKBreadcrumbsElement;
    };
    interface HTMLKBreadcrumbsItemElement extends Components.KBreadcrumbsItem, HTMLStencilElement {
    }
    var HTMLKBreadcrumbsItemElement: {
        prototype: HTMLKBreadcrumbsItemElement;
        new (): HTMLKBreadcrumbsItemElement;
    };
    interface HTMLKButtonElement extends Components.KButton, HTMLStencilElement {
    }
    var HTMLKButtonElement: {
        prototype: HTMLKButtonElement;
        new (): HTMLKButtonElement;
    };
    interface HTMLKCardElement extends Components.KCard, HTMLStencilElement {
    }
    var HTMLKCardElement: {
        prototype: HTMLKCardElement;
        new (): HTMLKCardElement;
    };
    interface HTMLKCarouselElement extends Components.KCarousel, HTMLStencilElement {
    }
    var HTMLKCarouselElement: {
        prototype: HTMLKCarouselElement;
        new (): HTMLKCarouselElement;
    };
    interface HTMLKCarouselItemElement extends Components.KCarouselItem, HTMLStencilElement {
    }
    var HTMLKCarouselItemElement: {
        prototype: HTMLKCarouselItemElement;
        new (): HTMLKCarouselItemElement;
    };
    interface HTMLKCheckboxElement extends Components.KCheckbox, HTMLStencilElement {
    }
    var HTMLKCheckboxElement: {
        prototype: HTMLKCheckboxElement;
        new (): HTMLKCheckboxElement;
    };
    interface HTMLKCollapseItemElement extends Components.KCollapseItem, HTMLStencilElement {
    }
    var HTMLKCollapseItemElement: {
        prototype: HTMLKCollapseItemElement;
        new (): HTMLKCollapseItemElement;
    };
    interface HTMLKCollapseListElement extends Components.KCollapseList, HTMLStencilElement {
    }
    var HTMLKCollapseListElement: {
        prototype: HTMLKCollapseListElement;
        new (): HTMLKCollapseListElement;
    };
    interface HTMLKCollapseMenuElement extends Components.KCollapseMenu, HTMLStencilElement {
    }
    var HTMLKCollapseMenuElement: {
        prototype: HTMLKCollapseMenuElement;
        new (): HTMLKCollapseMenuElement;
    };
    interface HTMLKCollapseParentElement extends Components.KCollapseParent, HTMLStencilElement {
    }
    var HTMLKCollapseParentElement: {
        prototype: HTMLKCollapseParentElement;
        new (): HTMLKCollapseParentElement;
    };
    interface HTMLKColumnElement extends Components.KColumn, HTMLStencilElement {
    }
    var HTMLKColumnElement: {
        prototype: HTMLKColumnElement;
        new (): HTMLKColumnElement;
    };
    interface HTMLKDialogElement extends Components.KDialog, HTMLStencilElement {
    }
    var HTMLKDialogElement: {
        prototype: HTMLKDialogElement;
        new (): HTMLKDialogElement;
    };
    interface HTMLKDialogActionsElement extends Components.KDialogActions, HTMLStencilElement {
    }
    var HTMLKDialogActionsElement: {
        prototype: HTMLKDialogActionsElement;
        new (): HTMLKDialogActionsElement;
    };
    interface HTMLKDialogBodyElement extends Components.KDialogBody, HTMLStencilElement {
    }
    var HTMLKDialogBodyElement: {
        prototype: HTMLKDialogBodyElement;
        new (): HTMLKDialogBodyElement;
    };
    interface HTMLKDialogContentElement extends Components.KDialogContent, HTMLStencilElement {
    }
    var HTMLKDialogContentElement: {
        prototype: HTMLKDialogContentElement;
        new (): HTMLKDialogContentElement;
    };
    interface HTMLKDialogHeaderElement extends Components.KDialogHeader, HTMLStencilElement {
    }
    var HTMLKDialogHeaderElement: {
        prototype: HTMLKDialogHeaderElement;
        new (): HTMLKDialogHeaderElement;
    };
    interface HTMLKDividerElement extends Components.KDivider, HTMLStencilElement {
    }
    var HTMLKDividerElement: {
        prototype: HTMLKDividerElement;
        new (): HTMLKDividerElement;
    };
    interface HTMLKDropdownElement extends Components.KDropdown, HTMLStencilElement {
    }
    var HTMLKDropdownElement: {
        prototype: HTMLKDropdownElement;
        new (): HTMLKDropdownElement;
    };
    interface HTMLKDropdownItemElement extends Components.KDropdownItem, HTMLStencilElement {
    }
    var HTMLKDropdownItemElement: {
        prototype: HTMLKDropdownItemElement;
        new (): HTMLKDropdownItemElement;
    };
    interface HTMLKElevationElement extends Components.KElevation, HTMLStencilElement {
    }
    var HTMLKElevationElement: {
        prototype: HTMLKElevationElement;
        new (): HTMLKElevationElement;
    };
    interface HTMLKGridElement extends Components.KGrid, HTMLStencilElement {
    }
    var HTMLKGridElement: {
        prototype: HTMLKGridElement;
        new (): HTMLKGridElement;
    };
    interface HTMLKIconElement extends Components.KIcon, HTMLStencilElement {
    }
    var HTMLKIconElement: {
        prototype: HTMLKIconElement;
        new (): HTMLKIconElement;
    };
    interface HTMLKImgElement extends Components.KImg, HTMLStencilElement {
    }
    var HTMLKImgElement: {
        prototype: HTMLKImgElement;
        new (): HTMLKImgElement;
    };
    interface HTMLKInputElement extends Components.KInput, HTMLStencilElement {
    }
    var HTMLKInputElement: {
        prototype: HTMLKInputElement;
        new (): HTMLKInputElement;
    };
    interface HTMLKLabelElement extends Components.KLabel, HTMLStencilElement {
    }
    var HTMLKLabelElement: {
        prototype: HTMLKLabelElement;
        new (): HTMLKLabelElement;
    };
    interface HTMLKListGroupElement extends Components.KListGroup, HTMLStencilElement {
    }
    var HTMLKListGroupElement: {
        prototype: HTMLKListGroupElement;
        new (): HTMLKListGroupElement;
    };
    interface HTMLKListItemElement extends Components.KListItem, HTMLStencilElement {
    }
    var HTMLKListItemElement: {
        prototype: HTMLKListItemElement;
        new (): HTMLKListItemElement;
    };
    interface HTMLKMenuElement extends Components.KMenu, HTMLStencilElement {
    }
    var HTMLKMenuElement: {
        prototype: HTMLKMenuElement;
        new (): HTMLKMenuElement;
    };
    interface HTMLKMenuContentElement extends Components.KMenuContent, HTMLStencilElement {
    }
    var HTMLKMenuContentElement: {
        prototype: HTMLKMenuContentElement;
        new (): HTMLKMenuContentElement;
    };
    interface HTMLKMenuNavElement extends Components.KMenuNav, HTMLStencilElement {
    }
    var HTMLKMenuNavElement: {
        prototype: HTMLKMenuNavElement;
        new (): HTMLKMenuNavElement;
    };
    interface HTMLKModalElement extends Components.KModal, HTMLStencilElement {
    }
    var HTMLKModalElement: {
        prototype: HTMLKModalElement;
        new (): HTMLKModalElement;
    };
    interface HTMLKNotificationElement extends Components.KNotification, HTMLStencilElement {
    }
    var HTMLKNotificationElement: {
        prototype: HTMLKNotificationElement;
        new (): HTMLKNotificationElement;
    };
    interface HTMLKNotificationGroupElement extends Components.KNotificationGroup, HTMLStencilElement {
    }
    var HTMLKNotificationGroupElement: {
        prototype: HTMLKNotificationGroupElement;
        new (): HTMLKNotificationGroupElement;
    };
    interface HTMLKNotificationItemElement extends Components.KNotificationItem, HTMLStencilElement {
    }
    var HTMLKNotificationItemElement: {
        prototype: HTMLKNotificationItemElement;
        new (): HTMLKNotificationItemElement;
    };
    interface HTMLKPaginatorElement extends Components.KPaginator, HTMLStencilElement {
    }
    var HTMLKPaginatorElement: {
        prototype: HTMLKPaginatorElement;
        new (): HTMLKPaginatorElement;
    };
    interface HTMLKProgressBarElement extends Components.KProgressBar, HTMLStencilElement {
    }
    var HTMLKProgressBarElement: {
        prototype: HTMLKProgressBarElement;
        new (): HTMLKProgressBarElement;
    };
    interface HTMLKRadioButtonElement extends Components.KRadioButton, HTMLStencilElement {
    }
    var HTMLKRadioButtonElement: {
        prototype: HTMLKRadioButtonElement;
        new (): HTMLKRadioButtonElement;
    };
    interface HTMLKRadioButtonGroupElement extends Components.KRadioButtonGroup, HTMLStencilElement {
    }
    var HTMLKRadioButtonGroupElement: {
        prototype: HTMLKRadioButtonGroupElement;
        new (): HTMLKRadioButtonGroupElement;
    };
    interface HTMLKRowElement extends Components.KRow, HTMLStencilElement {
    }
    var HTMLKRowElement: {
        prototype: HTMLKRowElement;
        new (): HTMLKRowElement;
    };
    interface HTMLKTabElement extends Components.KTab, HTMLStencilElement {
    }
    var HTMLKTabElement: {
        prototype: HTMLKTabElement;
        new (): HTMLKTabElement;
    };
    interface HTMLKTabItemElement extends Components.KTabItem, HTMLStencilElement {
    }
    var HTMLKTabItemElement: {
        prototype: HTMLKTabItemElement;
        new (): HTMLKTabItemElement;
    };
    interface HTMLElementTagNameMap {
        "ihg-button": HTMLIhgButtonElement;
        "k-avatar": HTMLKAvatarElement;
        "k-banner": HTMLKBannerElement;
        "k-banner-text": HTMLKBannerTextElement;
        "k-breadcrumbs": HTMLKBreadcrumbsElement;
        "k-breadcrumbs-item": HTMLKBreadcrumbsItemElement;
        "k-button": HTMLKButtonElement;
        "k-card": HTMLKCardElement;
        "k-carousel": HTMLKCarouselElement;
        "k-carousel-item": HTMLKCarouselItemElement;
        "k-checkbox": HTMLKCheckboxElement;
        "k-collapse-item": HTMLKCollapseItemElement;
        "k-collapse-list": HTMLKCollapseListElement;
        "k-collapse-menu": HTMLKCollapseMenuElement;
        "k-collapse-parent": HTMLKCollapseParentElement;
        "k-column": HTMLKColumnElement;
        "k-dialog": HTMLKDialogElement;
        "k-dialog-actions": HTMLKDialogActionsElement;
        "k-dialog-body": HTMLKDialogBodyElement;
        "k-dialog-content": HTMLKDialogContentElement;
        "k-dialog-header": HTMLKDialogHeaderElement;
        "k-divider": HTMLKDividerElement;
        "k-dropdown": HTMLKDropdownElement;
        "k-dropdown-item": HTMLKDropdownItemElement;
        "k-elevation": HTMLKElevationElement;
        "k-grid": HTMLKGridElement;
        "k-icon": HTMLKIconElement;
        "k-img": HTMLKImgElement;
        "k-input": HTMLKInputElement;
        "k-label": HTMLKLabelElement;
        "k-list-group": HTMLKListGroupElement;
        "k-list-item": HTMLKListItemElement;
        "k-menu": HTMLKMenuElement;
        "k-menu-content": HTMLKMenuContentElement;
        "k-menu-nav": HTMLKMenuNavElement;
        "k-modal": HTMLKModalElement;
        "k-notification": HTMLKNotificationElement;
        "k-notification-group": HTMLKNotificationGroupElement;
        "k-notification-item": HTMLKNotificationItemElement;
        "k-paginator": HTMLKPaginatorElement;
        "k-progress-bar": HTMLKProgressBarElement;
        "k-radio-button": HTMLKRadioButtonElement;
        "k-radio-button-group": HTMLKRadioButtonGroupElement;
        "k-row": HTMLKRowElement;
        "k-tab": HTMLKTabElement;
        "k-tab-item": HTMLKTabItemElement;
    }
}
declare namespace LocalJSX {
    interface IhgButton {
        "disabled"?: boolean;
        "label"?: string;
        "type"?: 'primary' | 'secondary';
    }
    interface KAvatar {
        "size"?: 'small' | 'medium' | 'large';
    }
    interface KBanner {
        "type"?: 'success' | 'error';
    }
    interface KBannerText {
    }
    interface KBreadcrumbs {
    }
    interface KBreadcrumbsItem {
        "current"?: boolean;
    }
    interface KButton {
        "color"?: 'primary' | 'secondary' | 'terciary';
        "disabled"?: boolean;
        "elevation"?: boolean;
        "shape"?: 'full' | 'round' | 'smooth';
        "size"?: 'large' | 'medium' | 'small';
    }
    interface KCard {
    }
    interface KCarousel {
        "showDots"?: boolean;
        "steps"?: number;
        "transitionDuration"?: number;
    }
    interface KCarouselItem {
    }
    interface KCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        "value"?: string;
    }
    interface KCollapseItem {
        "disabled"?: boolean;
    }
    interface KCollapseList {
    }
    interface KCollapseMenu {
        "position"?: 'right' | 'left';
    }
    interface KCollapseParent {
    }
    interface KColumn {
        "fluid"?: boolean;
        "size"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizelg"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizemd"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizesm"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
        "sizexl"?: | '1'
    | '2'
    | '3'
    | '4'
    | '5'
    | '6'
    | '7'
    | '8'
    | '9'
    | '10'
    | '11'
    | '12';
    }
    interface KDialog {
    }
    interface KDialogActions {
    }
    interface KDialogBody {
    }
    interface KDialogContent {
    }
    interface KDialogHeader {
    }
    interface KDivider {
    }
    interface KDropdown {
        "color"?: 'primary' | 'secondary' | 'terciary';
        "disabled"?: boolean;
        "helperText"?: string;
        "label"?: string;
        "validationState"?: '' | 'success' | 'error';
        "variant"?: 'button' | 'input' | 'table';
    }
    interface KDropdownItem {
        "checked"?: boolean;
        "disabled"?: boolean;
        "name"?: string;
        "onSelectChanged"?: (event: CustomEvent<any>) => void;
        "onValueChanged"?: (event: CustomEvent<{
    id: any;
    value: any;
    text: string;
  }>) => void;
        "value"?: string;
    }
    interface KElevation {
        "radius"?: string;
    }
    interface KGrid {
        "fluid"?: boolean;
    }
    interface KIcon {
        "name"?: | 'alert-circle'
    | 'assistant'
    | 'attachment'
    | 'bookmark-border'
    | 'bookmark'
    | 'cached'
    | 'check-circle'
    | 'close'
    | 'cloud-upload'
    | 'colorize'
    | 'delete'
    | 'done'
    | 'drag-indicator'
    | 'edit'
    | 'event'
    | 'file-copy'
    | 'finish-1'
    | 'finish-2'
    | 'finish-3'
    | 'flip-camera-ios'
    | 'school'
    | 'highlight-off'
    | 'info'
    | 'insert-drive-file'
    | 'keyboard-arrow-down'
    | 'keyboard-arrow-left'
    | 'keyboard-arrow-right'
    | 'keyboard-arrow-up'
    | 'menu'
    | 'network-wired'
    | 'notifications-active'
    | 'notifications'
    | 'person'
    | 'photo-camera'
    | 'playlist-add-check'
    | 'question-answer'
    | 'remove-red-eye'
    | 'ribbon'
    | 'search'
    | 'settings'
    | 'supervised-user-circle'
    | 'swap-vert'
    | 'swap-vert-down'
    | 'swap-vert-up'
    | 'tune'
    | 'view-week'
    | 'visibility-off'
    | 'add-circle'
    | 'bookmarks'
    | 'dashboard';
        "size"?: 'small' | 'medium' | 'large' | 'extra-large';
    }
    interface KImg {
        "alt"?: string;
        "fit"?: 'fill' | 'contain' | 'cover' | 'none' | 'scale-down';
        "height"?: number;
        "src"?: string;
        "width"?: number;
    }
    interface KInput {
        "disabled"?: boolean;
        "helperText"?: string;
        "label"?: string;
        "maxLength"?: number;
        "minLength"?: number;
        "name"?: string;
        "onValueChange"?: (event: CustomEvent<any>) => void;
        "type"?: 'text' | 'password' | 'email' | 'tel' | 'url' | 'number';
        "validationState"?: '' | 'success' | 'error';
        "value"?: string;
    }
    interface KLabel {
    }
    interface KListGroup {
    }
    interface KListItem {
    }
    interface KMenu {
        "disableDrawer"?: boolean;
        "hideDrawerLg"?: boolean;
        "hideDrawerMd"?: boolean;
        "hideDrawerSm"?: boolean;
        "hideDrawerXl"?: boolean;
        "hideDrawerXs"?: boolean;
        "menuKey"?: string;
        "onToggleMenu"?: (event: CustomEvent<{
    id: string;
    hideDrawerXs: boolean;
    hideDrawerSm: boolean;
    hideDrawerMd: boolean;
    hideDrawerLg: boolean;
    hideDrawerXl: boolean;
  }>) => void;
    }
    interface KMenuContent {
    }
    interface KMenuNav {
    }
    interface KModal {
        "hideCloseButton"?: boolean;
        "show"?: boolean;
    }
    interface KNotification {
        "notificationCount"?: number;
    }
    interface KNotificationGroup {
    }
    interface KNotificationItem {
        "alertColor"?: string;
        "isRead"?: boolean;
        "label"?: string;
        "time"?: string;
    }
    interface KPaginator {
        "currentPage"?: number;
        "totalPages"?: number;
    }
    interface KProgressBar {
        "value"?: number;
    }
    interface KRadioButton {
        "checked"?: boolean;
        "disabled"?: boolean;
        "name"?: string;
        "onValueChanged"?: (event: CustomEvent<{ value: any; id: String }>) => void;
        "value"?: string;
    }
    interface KRadioButtonGroup {
    }
    interface KRow {
        "spacing"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    }
    interface KTab {
    }
    interface KTabItem {
        "current"?: boolean;
        "disabled"?: boolean;
        "onValueChanged"?: (event: CustomEvent<{ value: boolean; id: String }>) => void;
    }
    interface IntrinsicElements {
        "ihg-button": IhgButton;
        "k-avatar": KAvatar;
        "k-banner": KBanner;
        "k-banner-text": KBannerText;
        "k-breadcrumbs": KBreadcrumbs;
        "k-breadcrumbs-item": KBreadcrumbsItem;
        "k-button": KButton;
        "k-card": KCard;
        "k-carousel": KCarousel;
        "k-carousel-item": KCarouselItem;
        "k-checkbox": KCheckbox;
        "k-collapse-item": KCollapseItem;
        "k-collapse-list": KCollapseList;
        "k-collapse-menu": KCollapseMenu;
        "k-collapse-parent": KCollapseParent;
        "k-column": KColumn;
        "k-dialog": KDialog;
        "k-dialog-actions": KDialogActions;
        "k-dialog-body": KDialogBody;
        "k-dialog-content": KDialogContent;
        "k-dialog-header": KDialogHeader;
        "k-divider": KDivider;
        "k-dropdown": KDropdown;
        "k-dropdown-item": KDropdownItem;
        "k-elevation": KElevation;
        "k-grid": KGrid;
        "k-icon": KIcon;
        "k-img": KImg;
        "k-input": KInput;
        "k-label": KLabel;
        "k-list-group": KListGroup;
        "k-list-item": KListItem;
        "k-menu": KMenu;
        "k-menu-content": KMenuContent;
        "k-menu-nav": KMenuNav;
        "k-modal": KModal;
        "k-notification": KNotification;
        "k-notification-group": KNotificationGroup;
        "k-notification-item": KNotificationItem;
        "k-paginator": KPaginator;
        "k-progress-bar": KProgressBar;
        "k-radio-button": KRadioButton;
        "k-radio-button-group": KRadioButtonGroup;
        "k-row": KRow;
        "k-tab": KTab;
        "k-tab-item": KTabItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ihg-button": LocalJSX.IhgButton & JSXBase.HTMLAttributes<HTMLIhgButtonElement>;
            "k-avatar": LocalJSX.KAvatar & JSXBase.HTMLAttributes<HTMLKAvatarElement>;
            "k-banner": LocalJSX.KBanner & JSXBase.HTMLAttributes<HTMLKBannerElement>;
            "k-banner-text": LocalJSX.KBannerText & JSXBase.HTMLAttributes<HTMLKBannerTextElement>;
            "k-breadcrumbs": LocalJSX.KBreadcrumbs & JSXBase.HTMLAttributes<HTMLKBreadcrumbsElement>;
            "k-breadcrumbs-item": LocalJSX.KBreadcrumbsItem & JSXBase.HTMLAttributes<HTMLKBreadcrumbsItemElement>;
            "k-button": LocalJSX.KButton & JSXBase.HTMLAttributes<HTMLKButtonElement>;
            "k-card": LocalJSX.KCard & JSXBase.HTMLAttributes<HTMLKCardElement>;
            "k-carousel": LocalJSX.KCarousel & JSXBase.HTMLAttributes<HTMLKCarouselElement>;
            "k-carousel-item": LocalJSX.KCarouselItem & JSXBase.HTMLAttributes<HTMLKCarouselItemElement>;
            "k-checkbox": LocalJSX.KCheckbox & JSXBase.HTMLAttributes<HTMLKCheckboxElement>;
            "k-collapse-item": LocalJSX.KCollapseItem & JSXBase.HTMLAttributes<HTMLKCollapseItemElement>;
            "k-collapse-list": LocalJSX.KCollapseList & JSXBase.HTMLAttributes<HTMLKCollapseListElement>;
            "k-collapse-menu": LocalJSX.KCollapseMenu & JSXBase.HTMLAttributes<HTMLKCollapseMenuElement>;
            "k-collapse-parent": LocalJSX.KCollapseParent & JSXBase.HTMLAttributes<HTMLKCollapseParentElement>;
            "k-column": LocalJSX.KColumn & JSXBase.HTMLAttributes<HTMLKColumnElement>;
            "k-dialog": LocalJSX.KDialog & JSXBase.HTMLAttributes<HTMLKDialogElement>;
            "k-dialog-actions": LocalJSX.KDialogActions & JSXBase.HTMLAttributes<HTMLKDialogActionsElement>;
            "k-dialog-body": LocalJSX.KDialogBody & JSXBase.HTMLAttributes<HTMLKDialogBodyElement>;
            "k-dialog-content": LocalJSX.KDialogContent & JSXBase.HTMLAttributes<HTMLKDialogContentElement>;
            "k-dialog-header": LocalJSX.KDialogHeader & JSXBase.HTMLAttributes<HTMLKDialogHeaderElement>;
            "k-divider": LocalJSX.KDivider & JSXBase.HTMLAttributes<HTMLKDividerElement>;
            "k-dropdown": LocalJSX.KDropdown & JSXBase.HTMLAttributes<HTMLKDropdownElement>;
            "k-dropdown-item": LocalJSX.KDropdownItem & JSXBase.HTMLAttributes<HTMLKDropdownItemElement>;
            "k-elevation": LocalJSX.KElevation & JSXBase.HTMLAttributes<HTMLKElevationElement>;
            "k-grid": LocalJSX.KGrid & JSXBase.HTMLAttributes<HTMLKGridElement>;
            "k-icon": LocalJSX.KIcon & JSXBase.HTMLAttributes<HTMLKIconElement>;
            "k-img": LocalJSX.KImg & JSXBase.HTMLAttributes<HTMLKImgElement>;
            "k-input": LocalJSX.KInput & JSXBase.HTMLAttributes<HTMLKInputElement>;
            "k-label": LocalJSX.KLabel & JSXBase.HTMLAttributes<HTMLKLabelElement>;
            "k-list-group": LocalJSX.KListGroup & JSXBase.HTMLAttributes<HTMLKListGroupElement>;
            "k-list-item": LocalJSX.KListItem & JSXBase.HTMLAttributes<HTMLKListItemElement>;
            "k-menu": LocalJSX.KMenu & JSXBase.HTMLAttributes<HTMLKMenuElement>;
            "k-menu-content": LocalJSX.KMenuContent & JSXBase.HTMLAttributes<HTMLKMenuContentElement>;
            "k-menu-nav": LocalJSX.KMenuNav & JSXBase.HTMLAttributes<HTMLKMenuNavElement>;
            "k-modal": LocalJSX.KModal & JSXBase.HTMLAttributes<HTMLKModalElement>;
            "k-notification": LocalJSX.KNotification & JSXBase.HTMLAttributes<HTMLKNotificationElement>;
            "k-notification-group": LocalJSX.KNotificationGroup & JSXBase.HTMLAttributes<HTMLKNotificationGroupElement>;
            "k-notification-item": LocalJSX.KNotificationItem & JSXBase.HTMLAttributes<HTMLKNotificationItemElement>;
            "k-paginator": LocalJSX.KPaginator & JSXBase.HTMLAttributes<HTMLKPaginatorElement>;
            "k-progress-bar": LocalJSX.KProgressBar & JSXBase.HTMLAttributes<HTMLKProgressBarElement>;
            "k-radio-button": LocalJSX.KRadioButton & JSXBase.HTMLAttributes<HTMLKRadioButtonElement>;
            "k-radio-button-group": LocalJSX.KRadioButtonGroup & JSXBase.HTMLAttributes<HTMLKRadioButtonGroupElement>;
            "k-row": LocalJSX.KRow & JSXBase.HTMLAttributes<HTMLKRowElement>;
            "k-tab": LocalJSX.KTab & JSXBase.HTMLAttributes<HTMLKTabElement>;
            "k-tab-item": LocalJSX.KTabItem & JSXBase.HTMLAttributes<HTMLKTabItemElement>;
        }
    }
}
